services:
  nextapp:
    container_name: bnc-web
    image: bnc-web:1.0.0
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BASE_URL_API=http://localhost:1323
        - BASE_URL_API=http://goapp:1323
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BASE_URL_API=http://localhost:1323
      - BASE_URL_API=http://goapp:1323
    depends_on:
      - goapp
  goapp:
    container_name: bnc-api
    image: bnc-api:1.0.0
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - GODOTENV=false
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_PORT=5432
    ports:
      - "1323:1323"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data
